ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.vibelog.ApplicationKt.module ]
    }
}

storage {
    driverClassName = "org.postgresql.Driver"
    jdbcURL = ${?SUPABASE_DB_URL}
    user = ${?SUPABASE_DB_USER}
    password = ${?SUPABASE_DB_PASSWORD}
}

gemini {
    apiKey = ${?GEMINI_API_KEY}
}
