ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.vibelog.ApplicationKt.module ]
    }
}

storage {
    driverClassName = "org.postgresql.Driver"
    jdbcURL = ${?SUPABASE_DB_URL}
    user = ${?SUPABASE_DB_USER}
    password = ${?SUPABASE_DB_PASSWORD}
    
    // Supabase S3 Protocol Settings
    s3Endpoint = "https://uwuumnraqdvemlsvrapr.storage.supabase.co/storage/v1/s3"
    s3Region = "ap-southeast-1"
    s3AccessKey = ${?SUPABASE_S3_ACCESS_KEY}
    s3SecretKey = ${?SUPABASE_S3_SECRET_KEY}
}

gemini {
    apiKey = ${?GEMINI_API_KEY}
}
